name: university_timetable
description: 轻屿课表应用 - 支持小米超级岛
publish_to: 'none'
version: 2.0.5-5+117
repository: https://github.com/Mutx163/mikcb
homepage: https://github.com/Mutx163/mikcb
issue_tracker: https://github.com/Mutx163/mikcb/issues
license: GPL-3.0-or-later

environment:
  sdk: ">=3.12.2 <4.0.0"
  flutter: ">=3.44.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.6.0
  cupertino_icons: ^1.0.8
  file_picker: ^11.0.3
  http: ^1.2.2
  package_info_plus: ^9.0.1
  share_plus: ^12.0.2
  crypto: ^3.0.6
  webdav_plus: ^1.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  flutter_markdown: ^0.7.7+1
  flutter_secure_storage: ^10.3.1
  webview_flutter: 4.14.1
  azlistview: ^2.0.0
  animations: ^2.0.11
  table_parser: ^1.0.1
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  fl_chart: ^1.2.0
  forui: ^0.23.0
  workmanager: ^0.9.0+3
  fast_gbk: ^1.0.0
  flutter_svg: ^2.3.0
  image: ^4.8.0
  flutter_miuix:
    git:
      url: https://github.com/Mutx163/flutter_miuix.git
      ref: 8d72a94a72ca4580b43ef2b5872ded3021815ccd
  liquid_glass_renderer: ^0.2.0-dev.4
  flutter_blackbox: ^0.7.0
  fountain_codes: ^1.0.0
  mobile_scanner: ^7.4.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/branding/
    - assets/donate/
    - assets/holidays/
    - assets/hyperfocus/
    - docs/releases/
    - assets/lan_edit/
    - assets/templates/
