// Auto-generated by: dart run flutter_blackbox:init --generate
// Re-run to regenerate after adding new libraries.
// ignore_for_file: depend_on_referenced_packages

import 'package:flutter/foundation.dart';
import 'package:flutter_blackbox/flutter_blackbox.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import 'services/app_http_client.dart';

// ── HttpBlackBoxAdapter ───────────────────────────────────────────────────────
// Observes all requests made through an http.Client.
// Auto-generated — safe to modify.

class HttpBlackBoxAdapter extends BlackBoxHttpAdapter {
  HttpBlackBoxAdapter([http.Client? client])
    : _client = client ?? http.Client() {
    this.client = _BlackBoxObservingClient(this, _client);
  }

  final http.Client _client;
  late final http.Client client;
  int _idCounter = 0;

  @override
  String get name => 'http';

  Future<http.StreamedResponse> observeSend(http.BaseRequest request) async {
    final id = 'http_${_idCounter++}_${DateTime.now().millisecondsSinceEpoch}';
    final startMs = DateTime.now().millisecondsSinceEpoch;
    final url = request.url.toString();

    onRequest(
      NetworkRequest(
        id: id,
        method: request.method,
        url: url,
        timestamp: DateTime.now(),
        headers: _sanitiseHeaders(request.headers),
        queryParameters: request.url.queryParameters,
      ),
    );

    final mock = await intercept(request.method, url);
    if (mock != null) {
      final durationMs = DateTime.now().millisecondsSinceEpoch - startMs;
      final bodyBytes = _encodeBody(mock.body);
      onResponse(
        NetworkResponse(
          requestId: id,
          statusCode: mock.statusCode,
          durationMs: durationMs,
          headers: mock.headers,
          body: mock.body,
          responseSizeBytes: bodyBytes.length,
        ),
      );
      return http.StreamedResponse(
        Stream.value(bodyBytes),
        mock.statusCode,
        headers: mock.headers,
        request: request,
      );
    }

    try {
      final response = await _client.send(request);
      final durationMs = DateTime.now().millisecondsSinceEpoch - startMs;

      // Never buffer a large or binary payload just to log it. This client is
      // the shared default for every service in debug/profile builds, including
      // range probes that can legitimately receive a whole APK when the server
      // ignores `Range:` — buffering there would blow up memory and turn the
      // caller's header timeout into a full-download timeout.
      if (_shouldPassThroughWithoutBuffering(response)) {
        onResponse(
          NetworkResponse(
            requestId: id,
            statusCode: response.statusCode,
            durationMs: durationMs,
            headers: response.headers,
            body: _passThroughBodyPlaceholder(response),
            responseSizeBytes: response.contentLength ?? 0,
          ),
        );
        return response;
      }

      final bytes = await response.stream.toBytes();
      String? bodyStr;
      try {
        bodyStr = utf8.decode(bytes);
      } catch (_) {
        bodyStr = '<binary data: ${bytes.length} bytes>';
      }
      onResponse(
        NetworkResponse(
          requestId: id,
          statusCode: response.statusCode,
          durationMs: durationMs,
          headers: response.headers,
          body: bodyStr,
          responseSizeBytes: bytes.length,
        ),
      );
      return http.StreamedResponse(
        Stream.value(bytes),
        response.statusCode,
        headers: response.headers,
        reasonPhrase: response.reasonPhrase,
        request: request,
      );
    } on Exception catch (e) {
      final durationMs = DateTime.now().millisecondsSinceEpoch - startMs;
      onResponse(
        NetworkResponse(
          requestId: id,
          statusCode: 0,
          headers: const {},
          durationMs: durationMs,
          failureType: NetworkFailureType.connection,
          body: e.toString(),
        ),
      );
      rethrow;
    }
  }

  /// Bodies above this are streamed straight through, unbuffered and unlogged.
  static const int _maxLoggedBodyBytes = 256 * 1024;

  /// Content types worth decoding into the Network panel as text.
  static bool _looksTextual(String? contentType) {
    if (contentType == null || contentType.isEmpty) {
      // Unknown type: allow, the size cap still protects us.
      return true;
    }
    final lower = contentType.toLowerCase();
    return lower.startsWith('text/') ||
        lower.contains('json') ||
        lower.contains('xml') ||
        lower.contains('yaml') ||
        lower.contains('javascript') ||
        lower.contains('x-www-form-urlencoded');
  }

  static bool _shouldPassThroughWithoutBuffering(
    http.StreamedResponse response,
  ) {
    final length = response.contentLength;
    if (length != null && length > _maxLoggedBodyBytes) {
      return true;
    }
    if (!_looksTextual(response.headers['content-type'])) {
      return true;
    }
    return false;
  }

  static String _passThroughBodyPlaceholder(http.StreamedResponse response) {
    final length = response.contentLength;
    final type = response.headers['content-type'] ?? 'unknown';
    final size = length == null
        ? 'unknown size'
        : '${(length / 1024).toStringAsFixed(1)} KB';
    return '<body not captured: $type, $size — streamed through '
        'to avoid buffering>';
  }

  Map<String, String> _sanitiseHeaders(Map<String, String> headers) {
    const redacted = {'authorization', 'cookie', 'set-cookie', 'x-api-key'};
    return {
      for (final e in headers.entries)
        e.key: redacted.contains(e.key.toLowerCase())
            ? '*** redacted ***'
            : e.value,
    };
  }

  List<int> _encodeBody(dynamic body) {
    if (body == null) return [];
    if (body is String) return utf8.encode(body);
    return utf8.encode(jsonEncode(body));
  }
}

class _BlackBoxObservingClient extends http.BaseClient {
  _BlackBoxObservingClient(this._adapter, this._inner);
  final HttpBlackBoxAdapter _adapter;
  final http.Client _inner;

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    return _adapter.observeSend(request);
  }

  @override
  void close() => _inner.close();
}

// ── SharedPrefsStorageAdapter ─────────────────────────────────────────────────
// Exposes SharedPreferences in the BlackBox Storage panel.
// Auto-generated — safe to modify.

class SharedPrefsStorageAdapter extends BlackBoxStorageAdapter {
  @override
  String get name => 'SharedPreferences';

  @override
  Future<Map<String, dynamic>> readAll() async {
    final prefs = await SharedPreferences.getInstance();
    return {for (final key in prefs.getKeys()) key: prefs.get(key)};
  }

  @override
  Future<void> write(String key, dynamic value) async {
    final prefs = await SharedPreferences.getInstance();
    if (value is bool) {
      await prefs.setBool(key, value);
    } else if (value is int) {
      await prefs.setInt(key, value);
    } else if (value is double) {
      await prefs.setDouble(key, value);
    } else if (value is String) {
      await prefs.setString(key, value);
    } else if (value is List<String>) {
      await prefs.setStringList(key, value);
    } else {
      await prefs.setString(key, value.toString());
    }
  }

  @override
  Future<void> delete(String key) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(key);
  }

  @override
  Future<void> clear() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.clear();
  }
}

/// Call this in your main() before runApp().
///
/// ```dart
/// void main() {
///   setupBlackBox();
///   runApp(const BlackBoxOverlay(child: MyApp()));
/// }
/// ```
///
/// Enabled only in debug and profile builds (`!kReleaseMode`).
void setupBlackBox({http.Client? httpClient}) {
  if (kReleaseMode) {
    return;
  }
  final httpAdapter = HttpBlackBoxAdapter(httpClient);
  setupAppHttpClientForBlackBox(httpAdapter.client);
  BlackBox.setup(
    httpAdapters: [httpAdapter],
    storageAdapters: [SharedPrefsStorageAdapter()],
    logAdapter: PrintLogAdapter(),
    trigger: const BlackBoxTrigger.floatingButton(),
    enabled: !kReleaseMode,
  );
}
