#!/usr/bin/env python3
"""Append serviceMsg ARB keys before the final closing brace."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "lib" / "l10n"

EN_BLOCK = r'''
  "serviceMsgImportFileUnrecognized": "Import failed. The file content could not be recognized.",
  "serviceMsgImportUseOverwriteForFullBackup": "This is a full data backup. Please import using overwrite current timetable.",
  "serviceMsgImportNoProfilesInBackup": "No recoverable timetables were found in the backup file.",
  "serviceMsgUnrecognizedMikcbDataFile": "Not a recognizable mikcb data file.",
  "serviceMsgMissingSettingsData": "Settings data is missing.",
  "serviceMsgUnrecognizedMikcbFullBackup": "Not a recognizable mikcb full backup file.",
  "serviceMsgMissingFullBackupData": "Complete backup data is missing.",
  "serviceMsgUseProfileBackupNotFull": "Use a timetable profile backup JSON, not a full data backup.",
  "serviceMsgUnrecognizedSyncSnapshot": "Not a recognizable mikcb cloud sync snapshot.",
  "serviceMsgMissingSyncTimetableData": "Cloud sync timetable data is missing.",
  "serviceMsgSyncSnapshotChecksumFailed": "Cloud sync snapshot verification failed.",
  "serviceMsgSyncSnapshotNoProfiles": "No recoverable timetables in the cloud sync snapshot.",
  "serviceMsgSyncSnapshotUnrecognized": "Cloud sync snapshot could not be recognized.",
  "serviceMsgTimeSchemeNotFound": "Time scheme not found.",
  "serviceMsgTimeSchemeConfigUnavailable": "Current timetable time configuration is unavailable.",
  "serviceMsgTimeSchemeNotFoundSelected": "Selected time scheme was not found.",
  "serviceMsgTimeSchemeSectionsInsufficient": "Selected time scheme does not have enough sections for sections {startSection}-{endSection}.",
  "@serviceMsgTimeSchemeSectionsInsufficient": {"placeholders": {"startSection": {"type": "int"}, "endSection": {"type": "int"}}},
  "serviceMsgSectionCountBelowUsage": "Section count cannot be less than the maximum section in use (section {requiredMaxSection}).",
  "@serviceMsgSectionCountBelowUsage": {"placeholders": {"requiredMaxSection": {"type": "int"}}},
  "serviceMsgSectionCountBelowUsageDetail": "Section count cannot be less than the maximum section in use (section {requiredMaxSection}). In use: {profileName} · {courseName} (weekday {dayOfWeek} sections {startSection}-{endSection}, {usageType})",
  "@serviceMsgSectionCountBelowUsageDetail": {"placeholders": {"requiredMaxSection": {"type": "int"}, "profileName": {"type": "String"}, "courseName": {"type": "String"}, "dayOfWeek": {"type": "int"}, "startSection": {"type": "int"}, "endSection": {"type": "int"}, "usageType": {"type": "String"}}},
  "serviceMsgAtLeastOneSectionRequired": "At least one section time must be kept.",
  "serviceMsgSectionEndMustAfterStart": "Section {sectionNumber} end time must be later than start time. Overnight classes are not supported.",
  "@serviceMsgSectionEndMustAfterStart": {"placeholders": {"sectionNumber": {"type": "int"}}},
  "serviceMsgSectionStartBeforePreviousEnd": "Section {sectionNumber} start time cannot be earlier than the previous section end time.",
  "@serviceMsgSectionStartBeforePreviousEnd": {"placeholders": {"sectionNumber": {"type": "int"}}},
  "serviceMsgPeriodStartTimeRequired": "Set the first section start time for periods that have sections.",
  "serviceMsgSectionCrossesMidnight": "Section {sectionNumber} would cross midnight. Overnight classes are not supported.",
  "@serviceMsgSectionCrossesMidnight": {"placeholders": {"sectionNumber": {"type": "int"}}},
  "serviceMsgClassDurationMustPositive": "Class duration must be greater than 0.",
  "serviceMsgBreakDurationMustNonNegative": "Break duration cannot be less than 0.",
  "serviceMsgAtLeastOnePeriodSection": "At least one period must have sections.",
  "serviceMsgInvalidTimeFormat": "Time format is invalid.",
  "serviceMsgLinkedCourseNotFound": "Linked course was not found.",
  "serviceMsgCourseNotFoundForDelete": "Course to delete was not found.",
  "serviceMsgCourseNotScheduledWeek": "This course is not scheduled in week {sourceWeek}.",
  "@serviceMsgCourseNotScheduledWeek": {"placeholders": {"sourceWeek": {"type": "int"}}},
  "serviceMsgCourseNotFoundForReschedule": "Course to reschedule was not found.",
  "serviceMsgTargetWeekOutOfRange": "Target week is outside the current semester range.",
  "serviceMsgAtLeastOneScheduleSlot": "At least one class time slot must be kept.",
  "serviceMsgCourseNameRequired": "Course name cannot be empty.",
  "serviceMsgBackupContentRequired": "Backup content cannot be empty.",
  "serviceMsgSpreadsheetFormatOrEncodingUnrecognized": "Could not recognize spreadsheet format or encoding. Save CSV as UTF-8 and try again.",
  "serviceMsgSpreadsheetXlsxParseFailed": "Failed to parse XLSX file: {error}",
  "@serviceMsgSpreadsheetXlsxParseFailed": {"placeholders": {"error": {"type": "String"}}},
  "serviceMsgSpreadsheetRowWarning": "Row {rowNumber}: {message}",
  "@serviceMsgSpreadsheetRowWarning": {"placeholders": {"rowNumber": {"type": "int"}, "message": {"type": "String"}}},
  "serviceMsgSpreadsheetWakeupInsufficientColumns": "WakeUp format needs at least 7 columns, but row {rowNumber} has only {columnCount}.",
  "@serviceMsgSpreadsheetWakeupInsufficientColumns": {"placeholders": {"rowNumber": {"type": "int"}, "columnCount": {"type": "int"}}},
  "serviceMsgWeekdayMustBe1To7": "Weekday must be between 1 and 7.",
  "serviceMsgCustomWeeksRequired": "Weeks cannot be empty.",
  "serviceMsgClassWeeksRequired": "Class weeks cannot be empty.",
  "serviceMsgStartWeekMustBeAtLeast1": "Start week must be at least 1.",
  "serviceMsgStartWeekExceedsSemester": "Start week {startWeek} exceeds semester week count {semesterWeekCount}.",
  "@serviceMsgStartWeekExceedsSemester": {"placeholders": {"startWeek": {"type": "int"}, "semesterWeekCount": {"type": "int"}}},
  "serviceMsgEndWeekBeforeStartWeek": "End week cannot be earlier than start week.",
  "serviceMsgWeeksRangeRequired": "Class weeks or start week + end week must be provided.",
  "serviceMsgFieldMustBeAtLeast1": "{field} must be at least 1.",
  "@serviceMsgFieldMustBeAtLeast1": {"placeholders": {"field": {"type": "String"}}},
  "serviceMsgFieldCannotBeLessThan": "{endField} cannot be less than {startField}.",
  "@serviceMsgFieldCannotBeLessThan": {"placeholders": {"startField": {"type": "String"}, "endField": {"type": "String"}}},
  "serviceMsgSectionOutOfRange": "Section {section} is outside the time scheme range (1-{maxSection}).",
  "@serviceMsgSectionOutOfRange": {"placeholders": {"section": {"type": "int"}, "maxSection": {"type": "int"}}},
  "serviceMsgFieldMustBeInteger": "{field} must be an integer.",
  "@serviceMsgFieldMustBeInteger": {"placeholders": {"field": {"type": "String"}}},
  "serviceMsgFieldCannotBeEmpty": "{field} cannot be empty.",
  "@serviceMsgFieldCannotBeEmpty": {"placeholders": {"field": {"type": "String"}}},
  "serviceMsgSpreadsheetEndWeekClamped": "Row {rowNumber}: end week {endWeek} exceeds semester week count {semesterWeekCount}; adjusted to {semesterWeekCount}.",
  "@serviceMsgSpreadsheetEndWeekClamped": {"placeholders": {"rowNumber": {"type": "int"}, "endWeek": {"type": "int"}, "semesterWeekCount": {"type": "int"}}},
  "serviceMsgSpreadsheetOddEvenBoth": "Row {rowNumber}: odd and even weeks cannot both be selected; treated as odd weeks.",
  "@serviceMsgSpreadsheetOddEvenBoth": {"placeholders": {"rowNumber": {"type": "int"}}},
  "serviceMsgFieldCourseName": "Course name",
  "serviceMsgFieldWeekday": "Weekday",
  "serviceMsgFieldStartSection": "Start section",
  "serviceMsgFieldEndSection": "End section",
  "serviceMsgFieldCustomWeeks": "Weeks",
  "serviceMsgFieldClassWeeks": "Class weeks",
  "serviceMsgFieldStartWeek": "Start week",
  "serviceMsgFieldEndWeek": "End week",
  "serviceMsgWeekStartInvalid": "{itemName}: week range start is invalid.",
  "@serviceMsgWeekStartInvalid": {"placeholders": {"itemName": {"type": "String"}}},
  "serviceMsgWeekRangeInvalid": "{itemName}: week range is invalid.",
  "@serviceMsgWeekRangeInvalid": {"placeholders": {"itemName": {"type": "String"}}},
  "serviceMsgWeekRangeTooLarge": "{itemName}: week range is too large. Please check.",
  "@serviceMsgWeekRangeTooLarge": {"placeholders": {"itemName": {"type": "String"}}},
  "serviceMsgWeekTokenUnrecognized": "{itemName}: unrecognized week token: {token}",
  "@serviceMsgWeekTokenUnrecognized": {"placeholders": {"itemName": {"type": "String"}, "token": {"type": "String"}}},
  "serviceMsgWeeksExceedSemesterClamped": "{itemName} contains weeks beyond semester week count {semesterWeekCount} ({weeks}); excess weeks were ignored.",
  "@serviceMsgWeeksExceedSemesterClamped": {"placeholders": {"itemName": {"type": "String"}, "semesterWeekCount": {"type": "int"}, "weeks": {"type": "String"}}},
  "serviceMsgAiResultNotObject": "AI result is not a valid JSON object. Copy the full JSON again.",
  "serviceMsgAiSchemaMustBe": "schema must be {schema}",
  "@serviceMsgAiSchemaMustBe": {"placeholders": {"schema": {"type": "String"}}},
  "serviceMsgAiCoursesMustBeArray": "courses must be an array.",
  "serviceMsgAiWarningsMustBeArray": "warnings must be a string array.",
  "serviceMsgAiWarningItemMustBeString": "Each warnings item must be a string.",
  "serviceMsgAiCourseNotObject": "courses[{index}] is not a valid object.",
  "@serviceMsgAiCourseNotObject": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiCourseNameEmpty": "courses[{index}].name cannot be empty.",
  "@serviceMsgAiCourseNameEmpty": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiCourseDayOfWeekInvalid": "courses[{index}].dayOfWeek must be between 1 and 7.",
  "@serviceMsgAiCourseDayOfWeekInvalid": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiCourseStartSectionInvalid": "courses[{index}].startSection must be at least 1.",
  "@serviceMsgAiCourseStartSectionInvalid": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiCourseEndSectionInvalid": "courses[{index}].endSection cannot be less than startSection.",
  "@serviceMsgAiCourseEndSectionInvalid": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiCourseCustomWeeksEmpty": "courses[{index}].customWeeks cannot be empty.",
  "@serviceMsgAiCourseCustomWeeksEmpty": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiCourseNatureInvalid": "courses[{index}].courseNature must be required or elective.",
  "@serviceMsgAiCourseNatureInvalid": {"placeholders": {"index": {"type": "int"}}},
  "serviceMsgAiUnknownFields": "{targetName} contains unsupported fields: {fields}",
  "@serviceMsgAiUnknownFields": {"placeholders": {"targetName": {"type": "String"}, "fields": {"type": "String"}}},
  "serviceMsgAiFieldMustBeString": "{field} must be a string.",
  "@serviceMsgAiFieldMustBeString": {"placeholders": {"field": {"type": "String"}}},
  "serviceMsgAiFieldMustBeInteger": "{field} must be an integer.",
  "@serviceMsgAiFieldMustBeInteger": {"placeholders": {"field": {"type": "String"}}},
  "serviceMsgAiWeekListInvalid": "{itemName} can only contain integers greater than or equal to 1.",
  "@serviceMsgAiWeekListInvalid": {"placeholders": {"itemName": {"type": "String"}}},
  "serviceMsgAiWeekListTypeInvalid": "{field} must be an integer array or week string.",
  "@serviceMsgAiWeekListTypeInvalid": {"placeholders": {"field": {"type": "String"}}},
  "serviceMsgNoReleaseAvailable": "No release has been published yet.",
  "serviceMsgNoReleaseWithPrerelease": "No stable or prerelease version is available yet.",
  "serviceMsgUpdateCheckHttpFailed": "Update check failed (HTTP {statusCode}).",
  "@serviceMsgUpdateCheckHttpFailed": {"placeholders": {"statusCode": {"type": "int"}}},
  "serviceMsgUpdateCheckNetworkFailed": "Network error. Unable to check for updates right now.",
  "serviceMsgUpdateDownloadUrlUntrusted": "Update download URL failed security validation.",
  "serviceMsgUpdateDownloadHttpFailed": "Download failed (HTTP {statusCode}).",
  "@serviceMsgUpdateDownloadHttpFailed": {"placeholders": {"statusCode": {"type": "int"}}},
  "serviceMsgUpdateOpenInstallerFailed": "Failed to open installer: {detail}",
  "@serviceMsgUpdateOpenInstallerFailed": {"placeholders": {"detail": {"type": "String"}}},
  "serviceMsgUpdateDownloadInstallError": "Download or installation error: {detail}",
  "@serviceMsgUpdateDownloadInstallError": {"placeholders": {"detail": {"type": "String"}}},
  "serviceMsgInvalidUrl": "Invalid URL.",
  "serviceMsgUpdateAvailablePrerelease": "A new prerelease version is available.",
  "serviceMsgUpdateAvailable": "A new version is available.",
  "serviceMsgAlreadyLatest": "You are already on the latest version.",
  "serviceMsgShareBackupText": "This is a full backup of the current timetable. Import it to restore courses and settings.",
  "serviceMsgShareBackupSubject": "Qingyu Timetable backup",
  "serviceMsgShareBackupSubjectNamed": "{profileName} - Qingyu Timetable backup",
  "@serviceMsgShareBackupSubjectNamed": {"placeholders": {"profileName": {"type": "String"}}},
  "serviceMsgShareFullBackupText": "This is a full data backup containing all timetables, the active timetable, and time schemes.",
  "serviceMsgShareFullBackupSubject": "Qingyu Timetable - full data backup",
  "serviceMsgInvalidRepositoryUrl": "Repository URL format is invalid.",
  "serviceMsgIncompleteGithubRepoUrl": "GitHub repository URL is incomplete.",
  "serviceMsgIncompleteRawGithubUrl": "raw.githubusercontent.com URL is incomplete.",
  "serviceMsgGithubOnlySupported": "Only GitHub repository URLs are supported.",
  "serviceMsgWarehouseNoSchoolsIndex": "No school or tool index was found.",
  "serviceMsgWarehouseNoAdapters": "No adapter information was found for {schoolName}.",
  "@serviceMsgWarehouseNoAdapters": {"placeholders": {"schoolName": {"type": "String"}}},
  "serviceMsgWarehouseFetchFailedMirror": "Unable to read the adapter repository. Tried {candidatesCount} mirror endpoints. Check your network or switch mirror in Version Update.",
  "@serviceMsgWarehouseFetchFailedMirror": {"placeholders": {"candidatesCount": {"type": "int"}}},
  "serviceMsgWarehouseFetchFailedGithub": "Unable to read the adapter repository on GitHub. Check your network or switch to a mirror in Version Update.",
  "serviceMsgManualInputCaptcha": "Enter the captcha manually, then tap Continue.",
  "serviceMsgManualInputPassword": "Enter the password manually. If it was auto-filled, tap Continue.",
  "serviceMsgMacroNoSteps": "No recorded steps.",
  "serviceMsgMacroUserCancelled": "Cancelled by user.",
  "serviceMsgMacroStepFailed": "Step {stepIndex}/{totalSteps} failed: {detail}",
  "@serviceMsgMacroStepFailed": {"placeholders": {"stepIndex": {"type": "int"}, "totalSteps": {"type": "int"}, "detail": {"type": "String"}}},
  "serviceMsgMacroNavigateUrlEmpty": "Navigation URL is empty.",
  "serviceMsgMacroNavigateUrlInvalid": "Invalid URL: {url}",
  "@serviceMsgMacroNavigateUrlInvalid": {"placeholders": {"url": {"type": "String"}}},
  "serviceMsgMacroFillSelectorEmpty": "Fill-field selector is empty.",
  "serviceMsgMacroElementNotFound": "Element not found: {selector}",
  "@serviceMsgMacroElementNotFound": {"placeholders": {"selector": {"type": "String"}}},
  "serviceMsgMacroClickSelectorEmpty": "Click selector is empty.",
  "serviceMsgMacroUrlPatternEmpty": "URL pattern is empty.",
  "serviceMsgMacroWaitSelectorEmpty": "Wait selector is empty.",
  "serviceMsgMacroManualInputDefault": "Manual action required.",
  "serviceMsgMacroPollTimeout": "{stepLabel} timed out ({timeoutSeconds}s){lastError}",
  "@serviceMsgMacroPollTimeout": {"placeholders": {"stepLabel": {"type": "String"}, "timeoutSeconds": {"type": "int"}, "lastError": {"type": "String"}}},
  "serviceMsgMacroReplayNavigate": "Navigating…",
  "serviceMsgMacroReplayFillField": "Filling form…",
  "serviceMsgMacroReplayClick": "Clicking…",
  "serviceMsgMacroReplayWaitUrl": "Waiting for navigation…",
  "serviceMsgMacroReplayWaitSelector": "Waiting for page element…",
  "serviceMsgMacroReplayWaitManual": "Waiting for user action…",
  "serviceMsgMacroReplayExecuteScript": "Running import script…",
  "serviceMsgMacroReplayDelay": "Waiting…",
  "serviceMsgMacroReplayFailed": "Failed: {detail}",
  "@serviceMsgMacroReplayFailed": {"placeholders": {"detail": {"type": "String"}}},
  "serviceMsgMacroReplayPaused": "Waiting for manual action: {reason}",
  "@serviceMsgMacroReplayPaused": {"placeholders": {"reason": {"type": "String"}}},
  "serviceMsgSupportDonorsLoadFailed": "Failed to load supporters list: {detail}",
  "@serviceMsgSupportDonorsLoadFailed": {"placeholders": {"detail": {"type": "String"}}},
  "serviceMsgStatisticsShareFailed": "Share failed: {detail}",
  "@serviceMsgStatisticsShareFailed": {"placeholders": {"detail": {"type": "String"}}},
  "serviceMsgAuthFailed": "Invalid username or password.",
  "serviceMsgAccessDenied": "Access denied.",
  "serviceMsgCertificateError": "Certificate validation failed.",
  "serviceMsgConnectionTimeout": "Connection timed out.",
  "serviceMsgConnectionFailed": "Could not connect to the server.",
  "serviceMsgInvalidResponse": "Invalid server response.",
  "serviceMsgSyncFailed": "Sync failed.",
  "serviceMsgUsageTypeOverride": "override time scheme",
  "serviceMsgUsageTypeProfile": "profile main time scheme"
'''

ZH_BLOCK = EN_BLOCK  # replaced below

ZH_TRANSLATIONS = {
    "Import failed. The file content could not be recognized.": "导入失败，文件内容无法识别",
    "This is a full data backup. Please import using overwrite current timetable.": "这是全部数据备份，请使用“覆盖当前课表”方式导入",
    "No recoverable timetables were found in the backup file.": "备份文件中没有可恢复的课表",
    "Not a recognizable mikcb data file.": "不是可识别的 mikcb 数据文件",
    "Settings data is missing.": "缺少设置数据",
    "Not a recognizable mikcb full backup file.": "不是可识别的 mikcb 全量备份文件",
    "Complete backup data is missing.": "缺少完整备份数据",
    "Use a timetable profile backup JSON, not a full data backup.": "请使用课表档案备份 JSON，而非全部数据备份",
    "Not a recognizable mikcb cloud sync snapshot.": "不是可识别的 mikcb 云同步快照",
    "Cloud sync timetable data is missing.": "缺少云同步课表数据",
    "Cloud sync snapshot verification failed.": "云同步快照校验失败",
    "No recoverable timetables in the cloud sync snapshot.": "云同步快照中没有可恢复的课表",
    "Cloud sync snapshot could not be recognized.": "云同步快照无法识别",
    "Time scheme not found.": "时间模板不存在",
    "Current timetable time configuration is unavailable.": "当前课表时间配置不可用",
    "Selected time scheme was not found.": "未找到所选时间模板",
    "Selected time scheme does not have enough sections for sections {startSection}-{endSection}.": "所选时间模板节次数不足，无法覆盖第 {startSection}-{endSection} 节",
    "Section count cannot be less than the maximum section in use (section {requiredMaxSection}).": "节次数量不能小于当前已使用的最大节次（第{requiredMaxSection}节）",
    "Section count cannot be less than the maximum section in use (section {requiredMaxSection}). In use: {profileName} · {courseName} (weekday {dayOfWeek} sections {startSection}-{endSection}, {usageType})": "节次数量不能小于当前已使用的最大节次（第{requiredMaxSection}节）。正在使用：{profileName} · {courseName}（周{dayOfWeek} {startSection}-{endSection}节，{usageType}）",
    "At least one section time must be kept.": "至少需要保留一节课的时间",
    "Section {sectionNumber} end time must be later than start time. Overnight classes are not supported.": "第 {sectionNumber} 节结束时间必须晚于开始时间，暂不支持跨 0 点课程",
    "Section {sectionNumber} start time cannot be earlier than the previous section end time.": "第 {sectionNumber} 节开始时间不能早于上一节的结束时间",
    "Set the first section start time for periods that have sections.": "请为有节次的时段设置第一节开始时间",
    "Section {sectionNumber} would cross midnight. Overnight classes are not supported.": "第 {sectionNumber} 节会跨到次日，当前暂不支持跨 0 点课程",
    "Class duration must be greater than 0.": "上课时长必须大于 0",
    "Break duration cannot be less than 0.": "课间时长不能小于 0",
    "At least one period must have sections.": "至少需要设置一个时段的节次数",
    "Time format is invalid.": "时间格式不正确",
    "Linked course was not found.": "关联的课程不存在",
    "Course to delete was not found.": "未找到要删除的课程",
    "This course is not scheduled in week {sourceWeek}.": "这门课在第 {sourceWeek} 周没有排课",
    "Course to reschedule was not found.": "未找到要调课的课程",
    "Target week is outside the current semester range.": "目标周次超出当前学期范围",
    "At least one class time slot must be kept.": "至少需要保留一个上课时间段",
    "Course name cannot be empty.": "课程名称不能为空",
    "Backup content cannot be empty.": "备份内容不能为空",
    "Could not recognize spreadsheet format or encoding. Save CSV as UTF-8 and try again.": "无法识别表格格式或编码，请将 CSV 另存为 UTF-8 后重试",
    "Failed to parse XLSX file: {error}": "XLSX 文件解析失败：{error}",
    "Row {rowNumber}: {message}": "第 {rowNumber} 行：{message}",
    "WakeUp format needs at least 7 columns, but row {rowNumber} has only {columnCount}.": "WakeUp 格式需要至少 7 列，但第 {rowNumber} 行只有 {columnCount} 列",
    "Weekday must be between 1 and 7.": "星期必须是 1-7",
    "Weeks cannot be empty.": "周数 不能为空",
    "Class weeks cannot be empty.": "上课周 不能为空",
    "Start week must be at least 1.": "开始周 必须大于等于 1",
    "Start week {startWeek} exceeds semester week count {semesterWeekCount}.": "开始周 {startWeek} 超过学期周数 {semesterWeekCount}",
    "End week cannot be earlier than start week.": "结束周 不能小于开始周",
    "Class weeks or start week + end week must be provided.": "上课周 或 开始周+结束周 必须填写",
    "{field} must be at least 1.": "{field} 必须大于等于 1",
    "{endField} cannot be less than {startField}.": "{endField} 不能小于{startField}",
    "Section {section} is outside the time scheme range (1-{maxSection}).": "节次 {section} 超出时间模板范围（1-{maxSection}）",
    "{field} must be an integer.": "{field} 必须是整数",
    "{field} cannot be empty.": "{field} 不能为空",
    "Row {rowNumber}: end week {endWeek} exceeds semester week count {semesterWeekCount}; adjusted to {semesterWeekCount}.": "第 {rowNumber} 行：结束周 {endWeek} 超过学期周数 {semesterWeekCount}，已调整为 {semesterWeekCount}",
    "Row {rowNumber}: odd and even weeks cannot both be selected; treated as odd weeks.": "第 {rowNumber} 行：单周与双周不能同时勾选，已按单周处理",
    "Course name": "课程名称",
    "Weekday": "星期",
    "Start section": "开始节数",
    "End section": "结束节数",
    "Weeks": "周数",
    "Class weeks": "上课周",
    "Start week": "开始周",
    "End week": "结束周",
    "{itemName}: week range start is invalid.": "{itemName} 周次起始值不合法",
    "{itemName}: week range is invalid.": "{itemName} 周次范围不合法",
    "{itemName}: week range is too large. Please check.": "{itemName} 周次范围过大，请检查",
    "{itemName}: unrecognized week token: {token}": "{itemName} 含有无法识别的周次：{token}",
    "{itemName} contains weeks beyond semester week count {semesterWeekCount} ({weeks}); excess weeks were ignored.": "{itemName} 含有超过学期周数 {semesterWeekCount} 的周次（{weeks}），已忽略超出部分",
    "AI result is not a valid JSON object. Copy the full JSON again.": "AI 结果不是合法对象，请重新复制完整 JSON",
    "schema must be {schema}": "schema 必须为 {schema}",
    "courses must be an array.": "courses 必须是数组",
    "warnings must be a string array.": "warnings 必须是字符串数组",
    "Each warnings item must be a string.": "warnings 中的每一项都必须是字符串",
    "courses[{index}] is not a valid object.": "courses[{index}] 不是合法对象",
    "courses[{index}].name cannot be empty.": "courses[{index}].name 不能为空",
    "courses[{index}].dayOfWeek must be between 1 and 7.": "courses[{index}].dayOfWeek 必须是 1-7",
    "courses[{index}].startSection must be at least 1.": "courses[{index}].startSection 必须大于等于 1",
    "courses[{index}].endSection cannot be less than startSection.": "courses[{index}].endSection 不能小于 startSection",
    "courses[{index}].customWeeks cannot be empty.": "courses[{index}].customWeeks 不能为空",
    "courses[{index}].courseNature must be required or elective.": "courses[{index}].courseNature 只能是 required 或 elective",
    "{targetName} contains unsupported fields: {fields}": "{targetName} 包含不支持的字段：{fields}",
    "{field} must be a string.": "{field} 必须是字符串",
    "{field} must be an integer.": "{field} 必须是整数",
    "{itemName} can only contain integers greater than or equal to 1.": "{itemName} 只能包含大于等于 1 的整数",
    "{field} must be an integer array or week string.": "{field} 必须是整数数组或周次字符串",
    "No release has been published yet.": "仓库还没有发布 Release。",
    "No stable or prerelease version is available yet.": "还没有可用的正式版或预发布版本。",
    "Update check failed (HTTP {statusCode}).": "检查更新失败（HTTP {statusCode}）。",
    "Network error. Unable to check for updates right now.": "网络异常，暂时无法检查更新。",
    "Update download URL failed security validation.": "更新下载地址未通过安全校验",
    "Download failed (HTTP {statusCode}).": "下载失败（HTTP {statusCode}）",
    "Failed to open installer: {detail}": "打开安装包失败: {detail}",
    "Download or installation error: {detail}": "下载或安装过程中出现错误: {detail}",
    "Invalid URL.": "地址无效",
    "A new prerelease version is available.": "发现新的预发布版本",
    "A new version is available.": "发现新版本",
    "You are already on the latest version.": "当前已经是最新版本",
    "This is a full backup of the current timetable. Import it to restore courses and settings.": "这是轻屿课表当前课表的完整备份文件，导入后可直接恢复课程和设置。",
    "Qingyu Timetable backup": "轻屿课表备份",
    "{profileName} - Qingyu Timetable backup": "{profileName} - 轻屿课表备份",
    "This is a full data backup containing all timetables, the active timetable, and time schemes.": "这是轻屿课表的全部数据备份文件，包含所有课表、当前选中课表和时间模板。",
    "Qingyu Timetable - full data backup": "轻屿课表 - 全部数据备份",
    "Repository URL format is invalid.": "仓库地址格式不正确",
    "GitHub repository URL is incomplete.": "GitHub 仓库地址不完整",
    "raw.githubusercontent.com URL is incomplete.": "raw.githubusercontent.com 地址不完整",
    "Only GitHub repository URLs are supported.": "当前只支持 GitHub 仓库地址",
    "No school or tool index was found.": "未读取到任何学校或工具索引",
    "No adapter information was found for {schoolName}.": "未读取到 {schoolName} 的适配器信息",
    "Unable to read the adapter repository. Tried {candidatesCount} mirror endpoints. Check your network or switch mirror in Version Update.": "暂时无法读取适配仓。已尝试 {candidatesCount} 个镜像线路均失败。请检查网络，或到「版本更新」里切到其他镜像线路后重试。",
    "Unable to read the adapter repository on GitHub. Check your network or switch to a mirror in Version Update.": "暂时无法读取适配仓。当前正在使用 GitHub 原始线路，请检查网络，或在「版本更新」里切到国内镜像后重试。",
    "Enter the captcha manually, then tap Continue.": "请手动输入验证码；完成后点击继续",
    "Enter the password manually. If it was auto-filled, tap Continue.": "请手动输入密码；如已自动填充请直接继续",
    "No recorded steps.": "没有录制的步骤",
    "Cancelled by user.": "用户取消",
    "Step {stepIndex}/{totalSteps} failed: {detail}": "第 {stepIndex}/{totalSteps} 步失败: {detail}",
    "Navigation URL is empty.": "导航 URL 为空",
    "Invalid URL: {url}": "无效的 URL: {url}",
    "Fill-field selector is empty.": "填充字段的选择器为空",
    "Element not found: {selector}": "未找到元素: {selector}",
    "Click selector is empty.": "点击元素的选择器为空",
    "URL pattern is empty.": "URL 模式为空",
    "Wait selector is empty.": "等待元素的选择器为空",
    "Manual action required.": "需要手动操作",
    "{stepLabel} timed out ({timeoutSeconds}s){lastError}": "{stepLabel} 超时（{timeoutSeconds}秒）{lastError}",
    "Navigating…": "正在导航...",
    "Filling form…": "正在填充表单...",
    "Clicking…": "正在点击...",
    "Waiting for navigation…": "等待页面跳转...",
    "Waiting for page element…": "等待页面元素...",
    "Waiting for user action…": "等待用户操作",
    "Running import script…": "正在执行导入脚本...",
    "Waiting…": "等待中...",
    "Failed: {detail}": "失败: {detail}",
    "Waiting for manual action: {reason}": "等待手动操作: {reason}",
    "Failed to load supporters list: {detail}": "加载鸣谢名单失败：{detail}",
    "Share failed: {detail}": "分享失败: {detail}",
    "Invalid username or password.": "账号或密码错误",
    "Access denied.": "没有访问权限",
    "Certificate validation failed.": "证书校验失败",
    "Connection timed out.": "连接超时",
    "Could not connect to the server.": "无法连接服务器",
    "Invalid server response.": "服务器响应无效",
    "Sync failed.": "同步失败",
    "override time scheme": "副时间表",
    "profile main time scheme": "课表主时间表",
}


def translate_block(en_block: str) -> str:
    zh = en_block
    for en, cn in ZH_TRANSLATIONS.items():
        zh = zh.replace(en, cn)
    return zh


def append_block(path: Path, block: str) -> None:
    text = path.read_text(encoding="utf-8").rstrip()
    if text.endswith("}"):
        text = text[:-1].rstrip()
        if not text.endswith(","):
            text += ","
        text += block + "\n}\n"
        path.write_text(text, encoding="utf-8")


def main() -> None:
    en_block = EN_BLOCK
    zh_block = translate_block(EN_BLOCK)
    append_block(ROOT / "app_en.arb", en_block)
    append_block(ROOT / "app_zh.arb", zh_block)
    for name in ("app_ja.arb", "app_ko.arb", "app_zh_TW.arb", "app_zh_HK.arb"):
        append_block(ROOT / name, en_block)


if __name__ == "__main__":
    main()
